#Preview all emails at http://localhost:3000/rails/mailers/user_mailer
class UserMailerPreview < ActionMailer::Preview
 def contact_form
 	UserMailer.contact_form("test@example.com", "John Test", "This is a test message generated by user_mailer_preview.rb")
 end
end
